export const demo_people = [
	{
		is_demo: true,
		id: '1-demo-amelia-earhart',
		name: "Amelia Earhart",
		first_name: "Amelia",
		last_name: "Earhart",
		images: ["https://faces.onl/demo/demo_1.jpg"],
		description: "",
		links: [],
		companies: [],
		emails: [],
		facts: [],
	},
	{
		is_demo: true,
		id: 'id-2-demo-marie-curie',
		name: "Marie Curie",
		first_name: "Marie",
		last_name: "Curie",
		images: ["https://faces.onl/demo/demo_2.jpg"],
		description: "",
		links: [],
		companies: [],
		emails: [],
		facts: [],
	},
	{
		is_demo: true,
		id: 'id-3-demo-martin-luther-king-jr',
		name: "Martin Luther King Jr.",
		first_name: "Martin",
		last_name: "Luther King Jr.",
		images: ["https://faces.onl/demo/demo_3.jpg"],
		description: "",
		links: [],
		companies: [],
		emails: [],
		facts: [],
	},
	{
		is_demo: true,
		id: 'id-4-demo-albert-einstein',
		name: "Albert Einstein",
		first_name: "Albert",
		last_name: "Einstein",
		images: ["https://faces.onl/demo/demo_4.jpg"],
		description: "",
		links: [],
		companies: [],
		emails: [],
		facts: [],
	}
];
