<script lang="ts">
	import { Alert } from '$lib/components';
	import {
		dataSyncMessage,
		dataSyncMessageShow,
		dataSyncMessageType
	} from '$lib/stores/data_stores';
</script>

<svelte:head>
	<script async defer src="https://apis.google.com/js/api.js" onerror="console.err"></script>

	<script async defer src="https://accounts.google.com/gsi/client" onerror="console.err"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "SoftwareApplication",
        "name": "Faces",
        "url": "https://faces.onl/",
        "author": {
          "@type": "Person",
          "name": "Chris Putnam"
        },
        "datePublished": CURRENT_DATE_STAMP,
        "applicationCategory": "Productivity"
      }
	</script>
</svelte:head>

<div class="background">
	<section>
		<nav data-sveltekit-reload>
			<a href="/">Quiz</a>
			| <a href="/metrics">Metrics</a>
			| <a href="/people">Manage People</a>
			| <a href="/about">About</a>
			| <a href="/terms-privacy">Terms & Privacy</a>
		</nav>

		{#if $dataSyncMessageShow}
			<Alert type={$dataSyncMessageType} message={$dataSyncMessage} />
		{/if}
	</section>

	<slot />
</div>

<style>
	.background {
		display: flex;
		padding: 20px;
		align-items: start;
		gap: 20px;
		flex-wrap: wrap;
	}

	section {
		width: 100%;
		display: flex;
		justify-content: space-between;
		gap: 20px;
		flex-wrap: wrap;
	}

	nav {
		background-color: #eee;
		padding: 10px;
		border-radius: 10px;
	}
</style>
