<svelte:head>
	<script async defer src="https://apis.google.com/js/api.js" onerror="console.err"></script>

	<script async defer src="https://accounts.google.com/gsi/client" onerror="console.err"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "SoftwareApplication",
        "name": "Faces",
        "url": "https://faces.onl/",
        "author": {
          "@type": "Person",
          "name": "Chris Putnam"
        },
        "datePublished": CURRENT_DATE_STAMP,
        "applicationCategory": "Productivity"
      }
	</script>
</svelte:head>

<div class="background">
	<nav data-sveltekit-reload>
		<a href="/">Quiz</a> | <a href="/metrics">Metrics</a> | <a href="/people">Manage People</a>
	</nav>

	<slot />
</div>

<style>
	.background {
		display: flex;
		padding: 20px;
		align-items: start;
		gap: 20px;
		flex-wrap: wrap;
	}

	nav {
		background-color: #eee;
		padding: 10px;
		border-radius: 10px;
	}
</style>
